# Executive summary {-}

**This report analyzes short-term accommodations (STRs) in the province of British Columbia (BC), with a particular focus on dedicated STRs and their impact on the province's housing conditions. It provides an overview of STRs in the province, including their type, geographic location and levels of commercial activity. It offers an overview of the STRs that are operated commercially, and presents a model that explains the impact of dedicated STRs on rent increases throughout the province. It illustrates market trends through five community case studies. Finally, it provides an analysis of regulatory options for STRs, using examples and laying out a set of best practices.**

\noindent\rule{\textwidth}{1pt}

**SHORT-TERM RENTALS IN BRITISH COLUMBIA: MARKET OVERVIEW**

- There are on a daily average 16,080 active STR listings in British Columbia housing units in 2021, which collectively earned $663.2 million in revenue.
- The average number of active listings declined by 32.2% compared to 2019, while revenue decreased by 19.9%.
- The percentage of STR listings operated as entire-home listings was 86.2% in 2021, noticeably more than 2019's 79.0%
- Revenue is distributed unevenly among hosts, with the top 10% of hosts earning 55.4% of revenues and the top 1% earning 25.2% of all revenues.
- Multilistings account for almost half (47.5%) of STR listings in the province, earning 52.7% of total host revenue.
- The Covid-19 pandemic has caused reservations to drop by 22.8% in 2020 compared to 2019, and continued decreasing by 12.1% in 2021 compared to 2020. Nightly prices on the other hand witnessed different trends depending on market type. In central cities and the rest of the large urban regions, prices fell precipitously in 2020, while prices increased substantially in smaller communities and resort towns.

**THE IMPACT OF SHORT-TERM RENTALS ON HOUSING AVAILABILITY AND AFFORDABILITY IN BRITISH COLUMBIA**

- At the end of 2021, short-term rentals were taking 13,730 housing units off of BC’s long-term
market, a 13.9% decline compared to 2019.
- Using a regression model, we found that an increase of one dedicated STR per 100 rental units predicts that average rents in the neighbourhood will be $44.97 higher.
- From 2016-2021, we estimate that, if there had been no commercial STRs, BC renters would have saved $2.0 billion in rent.
- During the 2017-2019 pre-pandemic period, the proliferation of dedicated STRs across BC accounts for fully 19.3% of the increases in rents which BC households were subjected to.
- In 2020, when the number of commercial STRs plummeted because of the pandemic, our estimate is that 2020 rents increased 29.9% less than they otherwise would have, because of the decrease in commercial STRs that year.
- If the province’s STR market returns to its pre-pandemic trajectory by the end of 2023, the loss of housing to STRs will be expected to drive up average monthly rents in medium and large cities in the province by $52.35 above their levels at the end of 2021.

**COMMUNITY CASE STUDIES**

- The reservations and nightly prices dropped dramatically in the City of Vancouver because of the Covid-19 pandemic. STR reservations from March 2020 through March 2022 have been only 35.7% of what would have been expected for this time period and prices were 18.9% lower than the pre-pandemic trend.
- We estimate that rents in Vancouver increased 97.6% less than they otherwise would have, because of the decrease in commercial STRs that year.
- In Richmond, during the 2017-2019 pre-pandemic period, the increase of dedicated STRs accounts for 37.2% of the increases in rents which Richmond households were subjected to.
- In Nanaimo, STR reservation from March 2020 through March 2022 have been only 44.8% of what would have been expected for this time, but, at the same time, average nightly prices have been elevated 13.5% over their pre-pandemic trend.
- During the summer high season in 2021 in Kelowna, average nightly prices were 23.4% higher than the pre-pandemic trend, consistent with the pattern observed provincially, where international travel was cancelled and diverted to regional destinations, causing STR demand outside the major cities to remain reasonable strong, while supply constraints led that demand to manifest as higher prices rather than more listings.
- If STR activity returns to pre-pandemic trends in Summerland, the revival in STR activity will drive up average monthly rents by $143.14 above their levels at the end of 2021.

**NAVIGATING SHORT-TERM RENTAL REGULATIONS**

- Vancouver's STR regulation shows an early success story in that the city has been effective at reducing the dedicated STRs which drive up housing costs comes from comparing Vancouver with peer cities nationally and with the rest of the Metro Vancouver region, bringing back 800 housing units to the long-term rental market.
- Toronto’s registration system was successful at shifting market behavior, but by diverting properties out of the system, instead of capturing them within the system. Indeed, by leaving the possibility for hosts to change the minimum stay to 28 days, the registration offers a loophole for hosts not to register.
- The province of Quebec is considering applying a mandatory STR registration system. The registration would be mandatory to all, would not put any significant conditions on the operation of an STR, and include a principal residence distinction.
- The key missing feature from Quebec’s registration system is that it does not require online platforms to be accountable for enforcing the rules by only permitting listing with license numbers to be displayed on their site.
- We believe that a successful STR regulation system in BC would entail regulators to decide on three tasks: 1. They must decide on the appropriate regulations for the jurisdiction. 2. they must gather the information necessary to enforce the rules 3. they must enforce the rules.
- A successful STR regulation system would require collaboration between the province and the municipalities, leveraging the province's capacities and the municipalities' local knowledge to ensure that a STR regulation system successfully addresses housing concerns related to short-term rentals.

\newpage