# Introduction {-}

In May 2022, the Urban Politics and Governance research group (UPGo) at McGill University was commissioned by the British Columbia Hotel Association (BCHA) to conduct market research and analysis on short-term rentals (STRs) in the province of British Columbia (BC), the impact of STRs on the province's housing market, and the policy options available for regulating STRs. Specifically, this report will address the following topics: 

- A general market overview of short-term rentals in the province, including the volume, revenue, type, size and distribution of units, the presence of dedicated commercial operations, and the impact of Covid-19 on the STR market.
- An analysis of the impact of dedicated STRs on housing availability and affordability in BC, specifically through an examination of the number of housing units converted to dedicated STRs and quantitative modelling to determine the impact of commercial STR prevalence on residential rents.
- A presentation of community case studies, using five municipalities representative of the different STR markets in the province.
- A set of regulatory recommendations, drawing on a set of Canadian examples and best practices.

Data and methodology are discussed in the Appendix, and all the code used to generate the analysis in the report is available online at https://github.com/UPGo-McGill/bc-report-2022.

\newpage