---
title: "Chapter 4. Navigating short-term rental regulation"
author: "David Wachsmuth, Maxime Belanger de Blois and Cloe St-Hilaire"
date: "31/05/2022"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

library(tidyverse)
library(slider)
qs::qload("output/data/ch_2.qsm")
col_palette <-
  c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```

The sentiments around short-term rentals are diverse. A study by Bolt and Wachsmuth (TKTK) has shown that the neighbourhoods who tended to have negative sentiments toward STRs are not necessarily the ones with high numbers of these operations, but rather the extent of the presence of housing vulnerability in the neighbourhoods. A neighbourhood with a large number of commercial STRs and high percentages of unaffordable housing, renter households and newcomers tend to be negatively disposed toward short-term rentals. In other words, when STRs make housing matters worse, communities will oppose them. In line with these findings, a growing number of municipalities and provinces both in Canada and globally have started enacting regulations around the operation of short-term rentals.

The governments can use multiple methods for going about regulating STRs. One of the most crucial elements for a successful regulation of STRs is for governments to make a distinction between home sharing and commercially-operated STRs. Home sharing should be encouraged while commercial STRs should be made illegal. The evidence suggests that the most effective way to regulate STRs is through principal-residence requirements with mandatory registration. All households wishful to operate a short-term rental could do so in their residence with a valid and unique registration number. We present two stories of municipalities having regulated STRs -- Vancouver and Toronto -- and also present the Province of Quebec's law project that aims to regulate STRs at the provincial level.

# Vancouver, the early success story

In April 2018, the City of Vancouver enacted regulations on the operations of short-term rentals in the City, defined as rentals offered for thirty or fewer consecutive days (City of
Vancouver, 2020a). Under these regulations, each STR operator is required to obtain a license for their rental unit, the license being valid for one year. The listing can only be operated out of the host's principal residence, either for the entire dwelling or for individual rooms. The registration is mandatory on any rental platform, although Airbnb is the only one that agreed to require hosts in Vancouver to fill out a license field in their online listing, to engage in data sharing, and to undertake operator education (City of Vancouver, 2020b). In August 2018, shortly before the City’s announced start date for enforcement of the registration system, Airbnb removed approximately 2,400 listings which had not received licenses, which amounted to 30.8% of all displayed listings. Using trend analysis, we estimated that, by mid-2019, the Vancouver STR regulation reduced active STR listings by 1,510, or 35.8%. We also estimated that the City's regulations have returned 810 housing units to the long-term market, compared to counter-factual scenarios where no regulations were put in place. This represents 38.9% of the average number of commercial STRs taking housing off the Vancouver market in the second half of 2019.

While there is no way to confirm which scenario would have happened in Vancouver if it were not for the regulations, we compared Vancouver's trajectory with that of Toronto and Montreal for all active listings and also commercial listings (which we identify as either FREH listings or multilistings). Toronto implemented STR regulations in early 2021: two years and a half after Vancouver. Montreal has varying borough-level STR regulations, but commercial operations are largely forbidden in central boroughs. However, with no registration system in place, it has been widely understood that Montreal’s enforcement mechanisms have not been sufficiently strong to significantly affect the operation of commercial STRs. Toronto and Montreal thus represent zero- or low-regulation cases with which to compare Vancouver (Figure TKTK).

The comparison shows that the active listings in Vancouver plummeted in comparison to that of Montreal and Toronto. The comparison is starker if we look more closely to the multilistings and FREH listings. Montreal’s FREH listings were growing at a 15.2% higher rate than Vancouver, while Toronto’s FREH growth rate was identical to Vancouver’s. Through 2017, Montreal’s multilistings were growing at a 6.9% higher rate than Vancouver, while Toronto’s were growing 2.1% faster. In the second half of 2019, by which point the temporary impacts of Airbnb’s mass listing removal in Vancouver would have subsided, the commercial side of Vancouver’s market looked dramatically different from either Montreal or Toronto. These differences strongly support the conclusion that the City of Vancouver’s regulations have durably reduced the commercial part of Vancouver’s STR market. We can also see these conclusions by comparing the Vancouver trajectory to that of the rest of the CMA (Figure TKTK).

# Toronto, another regulation perspective 

Starting in early 2021, all STRs in the City of Toronto must be registered. In early January, Airbnb removed 2,600 Toronto listings which had failed to do so. However, the overwhelming majority of Airbnb hosts have responded not by registering, but by setting a minimum rental length of 28 days, which exempts them from the registration requirement. To compare, in November of 2020, only 6.3% of Toronto listings had a minimum stay of 28 days or more, while at the beginning of February 2021 it was 72.2%. While it was too early to tell at the time of analysis the long-term impacts the regulations had on the Toronto STR market, we can see that offering an option for hosts not to register acts as a serious barrier to effective regulation. Toronto's registration system was successful at shifting market behavior, but by diverting properties out of the system, instead of capturing them within the system. 

# Provincial efforts at regulating STRs

To promote efficiency and prevent municipalities shifting the burden, the province should weigh in and establish a single registration system. This form of regulation is being considered by the Province of Quebec. In August 2021, a law project, Le projet de loi 100, was submitted to Quebec's National Assembly. These proposed regulations would make mandatory the registration of all short-term accommodations in the province, including but not limited to short-term rentals, hotels, camping sites, and B&Bs. While the proposed law is a good model, it is clear from the enforcement troubles experienced by municipalities attempting to regulate STRs that some additional elements should be considered.

Indeed, it is essential that a registration system should make the platforms accountable, by allowing only registered listings to be displayed on their site. The experience of other jurisdictions shows that any conditions that allow short-term rental hosts to avoid registration will be subject to enormous pressure to provide a loophole for bad actors. The province is in a strong position to launch and enact the registration system.

Another crucial element of every STR regulation is the regulation's capacity to differentiate between home sharing (i.e. principal residence) and commercial operations. The negative impacts of STRs, namely housing unaffordability, nuisance, and crime tend to be disproportionately distributed among commercially-operated STRs. The regulation of short-term rentals should not systematically encourage or discourage short-term rentals in relation to hotels, since the overall benefits are relatively similar. But there is a strong public policy case, particularly in cities, for regulations to systematically discourage commercial short-term rentals relative to casual short-term rentals, since the former are responsible for most of the negative impacts. Given the negative impact of STRs across British Columbia, the default approach of all municipalities should be to consider principal residence STRs only.






