---
title: "ch_model"
output: html_document
date: '2022-05-25'
---

```{r setup, include=FALSE}
library(here)
source(here("R", "01_startup.R"))

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

# Function for checking file modifications
mtime <- function(files) lapply(Sys.glob(files), function(x) file.info(x)$mtime)

qload(here("output", "/model_chapter.qsm"))

# Set this to TRUE to output PDF figures
build_figures <- TRUE
```

## Predict rent prices with STR activity

### Relationship between Frequently Rented Entire Home listings and rent prices

```{r freh_vs_rent}



```

```{r make_fig_CHAPNUM_1}

figure_CHAPNUM_1_fun <- function(regular = "", condensed = "") {

cmhc_str |> 
  filter(!is.na(freh_p_dwellings)) |> 
  group_by(type, year) |> 
  summarize(freh_p_dwellings = mean(freh_p_dwellings, na.rm = TRUE)) |> 
  ggplot(aes(year, freh_p_dwellings, color = type)) +
  geom_line()
  
}

if (build_figures) {
  ggsave(here("output", "figures", "figure_5_1.pdf"),
         plot = figure_CHAPNUM_1_fun("Futura", "Futura Condensed"),
         width = 8, height = 5, units = "in", useDingbats = FALSE)
  extrafont::embed_fonts(here("output", "figures", "figure_5_1.pdf"))
}

```


```{r make_fig_CHAPNUM_2}

find_outliers <- function(x) {
  q1 <- quantile(x, 0.25, na.rm = TRUE)
  q3 <- quantile(x, 0.75, na.rm = TRUE)
  iqr <- (q3 - q1) * 1.5
  which(x < q1 - iqr | x > q3 + iqr)
}

figure_CHAPNUM_2_fun <- function(regular = "", condensed = "") {

cmhc_str[-find_outliers(cmhc_str$freh_p_dwellings), ] |> 
  filter(!is.na(type)) |> 
  ggplot(aes(total_rent, freh_p_dwellings)) +
  geom_point(aes(color = type)) +
  geom_smooth(se = TRUE, method = "lm", level = 0.95, color = "black")
  
}

if (build_figures) {
  ggsave(here("output", "figures", "figure_5_1.pdf"),
         plot = figure_CHAPNUM_2_fun("Futura", "Futura Condensed"),
         width = 8, height = 5, units = "in", useDingbats = FALSE)
  extrafont::embed_fonts(here("output", "figures", "figure_5_1.pdf"))
}

```

